### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by luaxlab** [gavinlyonsrepo/ERM19264_UC1609#1]
Hello,

I just noticed you haven't set a license for this library, nor have you included a file named LICENSE or COPYING.
This means that, although your webpage says your libraries are open-source, it is unknown what you actually can do. Especially porting / forking of this library is difficult without knowing which terms apply.

If you want to go "do what ever you want" I'd recommend the MIT license.

Cheers

**Comment by gavinlyonsrepo** [comment]
Hi 

There is a licence file (LICENSE.md) in the extras folder.
I usually mention it in readme but forgot this time.
